language: 
- ruby
rvm:
- 2.3.0
jdk:
- oraclejdk8
cache: 
  bundler: true
install:
- nvm install 0.12
- nvm use 0.12
- npm install --global postcss-cli autoprefixer 
- bundle install --path vendor/bundle
- wget -O boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
- chmod 755 boot
- ./boot -V
script:
- bundle exec middleman build
deploy:
  provider: script
  script: sh deploy.sh
  skip_cleanup: true
  on:
    branch: 
    - master
    - production
env:
  global:
  - secure: "FA2yla6QKI9jpWGKiCMzCBa7ofBzbrBUMU9xInxtethNkCA5tHEXaFUkuvdpLu2IrgNzDkabCxI7Xawk5K1HCEQow+VwrwfkOEZVv2ZxDYW6Jn8sz4O2auHqqbuWHU3PRKODJCZgE4OIuXfsihCkc3VZX/ozLET7Koe6defwz13aZ80wLMSIwcF6AHresokBcSchv/HfmtxY6fEatGkhl99AH+fsVZeP3jaRISsGHT/c35bz3zOOVLL0NZ8/2SrQJYkfw7TENXWHiEG2mAikpHUzwsztd/wGyAvBldFl6usMKESyFPXQxgzameWnjQB5rASyztfa7HvVoD+CE/zgTJX0JU5t/xn3w1ozxxngFS1gqj9cC9Aup0g47lMQivqQtENQyw6dldxWmWR8qWUq5LZDYj9u71mH2N/spBEtSRChesLr9qpPsKMfb2WxKNQNm4ii3cy8VWlKL5Sxk9qqbWLMAGyY0Ixw2dxXrQdJyEPqkUcalXfraqb7EaI3Eu0beulWWMdro7oSRx9pqy62KKZIg54cONHyT5yQ4crI003d5tCIMQDEV1EAW+bJEqKQqDRdGThPOGy6749JkkPaP5uCBAlDzwB9RQ75Arox8bW4UdB4zAxKX2yLnEm4VTzxpuR5uYqU4hIgCDl6vDCUD9YqUfwyK/pNVYUhs0oOmLQ="